name: PC Virtual

on:
  workflow_dispatch:

jobs:
  pc-virtual:
    runs-on: ubuntu-24.04
    timeout-minutes: 360

    steps:
      - name: Instalar ambiente
        run: |
          sudo apt update
          sudo apt install -y xrdp xfce4 xfce4-goodies

      - name: Configurar XRDP
        run: |
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

          sudo useradd -m -s /bin/bash usuario
          echo 'usuario:Senha123!' | sudo chpasswd

          echo "startxfce4" > /home/usuario/.xsession
          sudo chown usuario:usuario /home/usuario/.xsession

          echo "XRDP iniciado"
          sudo systemctl status xrdp --no-pager

      - name: Manter ligado
        run: |
          echo "PC virtual funcionando"
          sleep 21600
