
name: PC Virtual

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pc-virtual:
    runs-on: ubuntu-24.04
    timeout-minutes: 350

    steps:
      - name: Instalar ambiente gráfico
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 xrdp xorgxrdp dbus-x11

          sudo useradd -m -s /bin/bash usuario
          echo 'usuario:Senha123!' | sudo chpasswd

          sudo mkdir -p /home/usuario
          printf '#!/bin/sh\nunset DBUS_SESSION_BUS_ADDRESS\nunset SESSION_MANAGER\nexec dbus-launch --exit-with-session startxfce4\n' | sudo tee /home/usuario/.xsession
          sudo chown usuario:usuario /home/usuario/.xsession
          sudo chmod 755 /home/usuario/.xsession

          sudo adduser xrdp ssl-cert
          sudo systemctl enable xrdp
          sudo systemctl restart xrdp
          sudo systemctl status xrdp --no-pager
          sudo ss -ltnp | grep 3389

      - name: Conectar Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Mostrar IP do PC
        run: |
          echo "IP DO PC:"
          tailscale ip -4
          echo "Porta de acesso: 3389"

      - name: Manter PC ligado
        run: sleep 21000
        
