name: PC Virtual

on:
  workflow_dispatch:

jobs:
  pc-virtual:
    runs-on: ubuntu-24.04
    timeout-minutes: 350

    steps:
      - name: Instalar PC
        run: |
          sudo apt update
          sudo apt install -y xrdp xfce4

          sudo systemctl enable xrdp
          sudo systemctl start xrdp

          sudo useradd -m -s /bin/bash usuario
          echo 'usuario:Senha123!' | sudo chpasswd

          sudo sh -c "echo 'startxfce4' > /home/usuario/.xsession"
sudo chown usuario:usuario /home/usuario/.xsession
sudo chmod 644 /home/usuario/.xsession

      - name: Conectar Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Mostrar endereço do PC
        run: |
          echo "IP DO PC:"
          tailscale ip -4

          echo "XRDP:"
          sudo systemctl status xrdp --no-pager

      - name: Manter ligado
        run: |
          sleep 21000
